const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#00BFFF",
    background: "#000000",
    foreground: "#ffffff",
    card: "#1a1a1a",
    cardForeground: "#ffffff",
    primary: "#00BFFF",
    primaryForeground: "#000000",
    secondary: "#2a2a2a",
    secondaryForeground: "#ffffff",
    muted: "#1a1a1a",
    mutedForeground: "#888888",
    accent: "#00BFFF",
    accentForeground: "#000000",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#2a2a2a",
    input: "#2a2a2a",
  },
  dark: {
    text: "#ffffff",
    tint: "#00BFFF",
    background: "#000000",
    foreground: "#ffffff",
    card: "#1a1a1a",
    cardForeground: "#ffffff",
    primary: "#00BFFF",
    primaryForeground: "#000000",
    secondary: "#2a2a2a",
    secondaryForeground: "#ffffff",
    muted: "#1a1a1a",
    mutedForeground: "#888888",
    accent: "#00BFFF",
    accentForeground: "#000000",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#2a2a2a",
    input: "#2a2a2a",
  },
  radius: 12,
};

export default colors;
